[package]
name = "tetris-with-wasm"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
js-sys = "0.3.69"
rand = "0.8.5"
wasm-bindgen = "0.2.92"
wasm-react = "0.3.2"
